### ISSUE TITLE
Enrich data provided by ember deploy:list

### ISSUE THREAD

**Issue by achambers** [ember-cli-deploy/ember-cli-deploy#305]
Creating this issue to track discussion around enriching the data available in ember deploy:list

@mmun started a discussion on this in slack with @lukemelia and I thought this might be a good place to carry on the discussion.

**Comment by mmun** [comment]
Inspiration from `heroku releases`:

![screen_shot_2015-11-13_at_12 03 04_pm_360](https://cloud.githubusercontent.com/assets/1151810/11250035/683ce508-8df8-11e5-92d8-47f7400dbb50.png)

**Comment by mmun** [comment]
Here is the plan that @ghedamat and I came up with:

### ember-cli-deploy-revision-data
It should be more extensible. Specifically, I'd like to be able to store SCM information about the commit (commit author, commit message, etc.). Instead of specifying `type: 'file-hash'` we are considering an API like:
```
revisionData: {
  key: 'file-hash',
  scm: 'git'
}
```

or with options as 

```
revisionData: {
  key: { type: 'file-hash', filePattern: 'my-index.html' },
  scm: 'git'
}
```

This is the main open problem we all need to agree about.

### ember-cli-deploy-redis
It should persist _all_ revision data in `${keyPrefix}:revision-data:${revisionKey}` as a string of JSON.

### ember-cli-deploy-display-revisions
It should allow users to configure what columns are shown.

**Comment by lukemelia** [comment]
This plan sounds good @mmun and @ghedamat. I would add for ember-cli-deploy-redis changes that these keys should be cleaned up in the same way that the revision content keys are cleaned up over time.

**Comment by ghedamat** [comment]
@lukemelia agreed, will clarify it above

**Comment by ghedamat** [comment]
current status (with the work in the 3 linked PRs)
https://gsnaps.s3.amazonaws.com/screencast_2016-03-19_19-22-40.mp4

/cc @lukemelia @mmun

**Comment by mmun** [comment]
:bow: :pray: :tada:

**Comment by ghedamat** [comment]
closing for now as I believe we addressed this
