### ISSUE TITLE
Make it easier to disable plugins for certain deploy targets

### ISSUE THREAD

**Issue by lukemelia** [ember-cli-deploy/ember-cli-deploy#307]
Currently, the only mechanism for disabling a plugin for a specific deployTarget is to specify the plugins array for it, which means figuring out which plugins you have active, and in what order they are, and keeping that list up to date.

It would be nice to make this less challenging. Some ideas:

1. an “excludePlugins” array
2. make verbose mode output the array of plugins being used, in the order they are being used in, so people have an easy starting point if they need to configure it
3. a per-plugin “ignore” or "disabled" config

The downside to 1 and 3 is that they make the `plugins` array more confusing to understand if used in combination. Thoughts welcome.

**Comment by ghedamat** [comment]
the few convos I had on the subject showed that people (myself first when I started) find the `plugins` array confusing

for sure it could be resolved by more docs
and I think adding the plugins array to the verbose output is a very good idea

that said I kind of like a "disabled" option as well on a per plugin basis.. 

I guess I'm saying I'm 50/50?

**Comment by sd** [comment]
My name is Sebastian Delmont, and I endorse this message

**Comment by lukemelia** [comment]
![His name is Sebastian Delmont, and he endorses this message](http://i.imgur.com/727Hj6n.png)

**Comment by rwjblue** [comment]
Could this be a function instead of exclude array? 

Something like this could be the default:

    shouldIncludePlugin: function(pluginName) { 
      return true;
    },

Seems less rigid than the include/exclude array concepts...

**Comment by lukemelia** [comment]
Another idea: make current `plugins` property able to accept a function which receives the "natural" plugins array.

```js
plugins: ['build', 's3', 'redis'] // already works
```

```js
 // proposed to also work
plugins: function(allPlugins){
  // return an array of plugins by removing elements, changing order, etc.
  return allPlugins.filter(function(p) {
    return p !== 's3';
  });
}
```

**Comment by ghedamat** [comment]
I love this!

**Comment by lukemelia** [comment]
In addition to the function approach, we could a more declarative option for the `plugins` config option: `{ exclude: ['ssh-tunnel'] }`

**Comment by ghedamat** [comment]
confirm, and maybe we ignore `exclude` if plugins is defined?

**Comment by achambers** [comment]
@lukemelia I was just about to suggest the plugins function that passes in the array of plugins also. Love that. That way a user can filter and reorder as desired. :+1: from me

**Comment by lukemelia** [comment]
@ghedamat if these three options (array, function, and object with `exclude` property) are all potential values for `plugins`, then it's impossible for them to conflict.

**Comment by duizendnegen** [comment]
I would want to propose an extension of the `exclude` (and `plugins`) - namely a function which gets evaluated at every plugin step, with an optional second parameter with the plugin step name, like so:

```javascript
exclude: function(plugin, step) {
   if(plugin === 's3' && step === 'fetchRevisions') return false;
   return true;
}
```

this would enable more flexibility to pick 'n mix - there were some anticipated & some encountered use cases to disable just certain steps from plugins.
Looking forward to feedback.

**Comment by lukemelia** [comment]
@duizendnegen Your suggestion would give the end consumer a ton of power but also break expectations of plugin authors, who can't rely on what other plugins they are running with, but can at least rely that their own previous hooks were run. I would want to see concrete examples of why this power/complexity is warranted.

**Comment by duizendnegen** [comment]
In that case, let's leave it out & wait for concrete examples.
I remember one running Redis+some other index.html plugin, wanting to only
list revisions on the latter - no idea what was the use case though

**Comment by mansona** [comment]
Hey all, since you are looking for a use case I thought I would weigh in here. We are currently using the ssh-tunnel plugin to be able to connect to Redis behind a firewall and I wanted to test my deployment pipeline locally. I needed a way to disable the ssh-tunnel plugin for my local environment (see the issue here https://github.com/ember-cli-deploy/ember-cli-deploy-ssh-tunnel/issues/6 )

This first came up because my expectation was that if i didn't give ssh-tunnel a host or username it wouldn't create a tunnel. The issue I faced was that the ssh-tunnel plugin had required config fields and it just kept complaining everything I tried. 

Don't know if this helps as a usecase but if anyone has any questions just let me know 👍

**Comment by ef4** [comment]
I think some of the API design difficulty here is happening because `plugins` mixes two separate concerns: (1) which plugins to run, (2) what order to run them in.

For controlling whether or not to run, a single `enabled` flag on each plugins' config is very clear:

    // Disable by default
    ENV.somePlugin.enabled = false;

    // Enable for a single target
    if (deployTarget === 'development') {
      ENV.somePlugin.enabled = false;
    }

For controlling order, the most important thing to express is dependencies between plugins. Both plugin authors and users may want to express dependencies, and ember-cli-deploy can resolve a correct `plugins` array that satisfies the constraints.

    ENV.somePlugin.runsAfter = ['s3'];
    ENV.somePlugin.runsBefore = ['s3-index'];
