### ISSUE TITLE
Show warning/error if no plugin implementing a hook is loaded

### ISSUE THREAD

**Issue by dschmidt** [ember-cli-deploy/ember-cli-deploy#386]
Hey,

so tonight I was wondering why no revisions were printed out with `deploy:list` and assumed that `ember-cli-deploy-redis` itself or my redis db was broken. Then I realized I should probably install `ember-cli-deploy-display-revisions` ... still nothing working. Took me some more time to realize I needed to explicitly load the plugin because I'm having an explicit list of plugins with alias names.

Would have been nice if the pipeline (or whatever) would have at least warned me that there is no plugin implementing the displayRevisions hook.

BR,
Dominik

**Comment by ghedamat** [comment]
@dschmidt I was thinking something similar after our convo yesterday

customizing the `plugins` turns off auto-load entirely and maybe we should make that even more explicit in the guides

that said, we should try to find a way to add that check to `deploy:list` so that it will work both if you forgot to alias the plugin or (more common) if you forgot to install it

**Comment by dschmidt** [comment]
Exactly :)

**Comment by ghedamat** [comment]
@dschmidt let me know if #406 closes this for you, otherwise feel free to reopen

**Comment by dschmidt** [comment]
Cool, thanks!
