### ISSUE TITLE
Display revisions shows no output (but revisions exist)

### ISSUE THREAD

**Issue by brandonrich** [ember-cli-deploy/ember-cli-deploy#400]
Deployment to s3 is working.  Awesome!  But I can never get the CLI to display revisions.  I have to check s3 (or git log) to see what to activate.  

I have 4 development deployment tags in s3 and can switch to them w/ no problem.  I just can't display them:
> ember deploy:list development --verbose
(snip)
+- setup
|
+- fetchRevisions
|  |
|  +- s3-index
|
+- displayRevisions
|
+- teardown
|
Pipeline complete

Also, is deployment supposed to activate the latest automatically?  It doesn't do that.

**Comment by ghedamat** [comment]
@brandonrich quick question

do you have https://github.com/ember-cli-deploy/ember-cli-deploy-display-revisions installed?

**Comment by achambers** [comment]
Beat me to it @ghedamat. I was just asking the same thing ;)

**Comment by ghedamat** [comment]
passing `--activate` to the deploy command will do automatic activation

http://ember-cli-deploy.github.io/ember-cli-deploy/docs/v0.6.x/usage-overview/

**Comment by achambers** [comment]
You can also set

```
pipeline: {
  activateOnDeploy: true
}
```

if you want it to activate every time.

**Comment by brandonrich** [comment]
Ha!  Perfect, thanks!  Installing that package did it, of course.  These tools are really great, but they are loosely coupled, huh :-)

Thanks also for the tip about activation.

Is there a way to use ember-cli-deploy to delete remote revisions?

**Comment by achambers** [comment]
>  but they are loosely coupled

Yep. But that's kind of the point. Although that can make it difficult to know what to reach for. The reality is though, deployment is not always straight forward and everyone's use case differs slightly. So there is no real concept of Quick Start guide for deployment because you have to know some level about what it is you're trying to do.

Having said that, the display revisions is not immediately obvious and we can certainly improve our communication around that plugin.

> Is there a way to use ember-cli-deploy to delete remote revisions?

Nope. This is something that we just have not really seen as priority. With such a low cost of storing assets etc, the cost of developing that functionality just hasn't been justified compared to shipping other features. If the community need it enough then maybe someone will contribute that functionality. Maybe it's you :)

**Comment by brandonrich** [comment]
Maybe once I get a little more ember experience!  Thanks so much for your quick and thorough responses.
