### ISSUE TITLE
Needed: a consistent way to modify config

### ISSUE THREAD

**Issue by jrjohnson** [ember-cli-deploy/ember-cli-deploy#429]
Each plugin has configuration options, and sometimes they can get complicated.  As a user if I override a large configuration section I run the risk of missing a future improvement to the plugin because I'm no longer using the default values.  As an example in the json-config plugin the jsonBlueprint option is a large object with several keys.  The only way to override it currently is to replace the entire default object with my own.

After some discussion with @achambers a better approach might be to create a callback in deploy.js which would get the default configuration object for each plugin and then return a modified one.  This would make it much easier to inherit and preserve defaults while overriding only needed options.

I see three possible ways to specify this:
1) Each option in a plugin could be specified as a callback, eg:

``` javascript
ENV['s3'] = {
    filePattern(filePath){
      return filePath += ',*.json';
    }
  }
```

2) Each plugin could be overridden, eg:

``` javascript
ENV['s3'] = {
    config(defaultConfig){
      defaultConfig.filePath += '*.json';
      return defaultConfig;
    }
  }
```

3) The entire config tree could be modified:

``` javascript
ENV.config(defaultConfig){
    defaultConfig['s3'].filePath += '*.json';
    return defaultConfig;
}
```

I think option 2 provides the right balance of specificity and usefulness.  I'm willing to take a shot at implementing this but I wanted to open it up to discussion first to see if this is a good approach and what the API should look like for users.

All comments welcome,

**Comment by achambers** [comment]
Awesomeness. I had something slightly different in mind in terms of the API, but totally for the approach. Would be great to be able to get access to the original default value and modify that instead of stomping on top of it. 

I'm on my phone at the moment but I'll endeavour to write an example when on my laptop later. 

Love to hear your thoughts @lukemelia, @ghedamat @levelbossmike

**Comment by LevelbossMike** [comment]
Though I have not felt this pain before this definitely sounds like a great solution for configuration properties that return a "complex" object like `jsonBlueprint`.

Because this changes the current behaviour quite significantly I guess this would need to be be considered a breaking change right?

**Comment by jrjohnson** [comment]
I'm not sure it needs to be breaking if the right name is selected. If no plugins are using the 'config' key then adding it would not cause conflicts. Since I suspect config is probably used somewhere maybe something like 'pluginConfig' could work?

it could easily be treated as breaking to make it easy to know exactly when it was supported for documentation purposes.

**Comment by achambers** [comment]
So, my thinking was slightly different and it shouldn't be a breaking change. Without having thought about the underlying implementation details too much, I was thinking some thing like this might be helpful:

### BEFORE
```javascript
ENV.s3 = {
  filePattern: '**/*.{js,css,png,gif,ico,jpg,map,xml,txt,svg,swf,eot,ttf,woff,woff2,otf,exe}'
}
```

### AFTER

```javascript
ENV.s3 = {
  filePattern: function() {
    var old = this._super();
    return old.replace('}', ',exe}');
  }
}
```

So, I was hoping we could get access to the old default value somehow in order to modify it and return instead of having to duplicate what the default value was.

I guess we need to look at how the config is created and see if there is someway of doing this. I'm sort of likening it to calling `this._super()` in `init` in Ember components although I'm sure how that's actually implemented.

Anyway, those were my thoughts. I was hoping to not have to introduce any new special property if possible.

**Comment by achambers** [comment]
Another thought is we could pass the default value in to the function if there is one, alongside the context that is already passed in. Like so (most similar to item #2 in the description):

```
ENV.s3 = {
  filePattern: function(context, defaultValue) {
    return defaultValue.replace('}', ',exe}');
  }
};
```

This would not be a breaking change as we would be adding a new argument. 

Thoughts?

**Comment by achambers** [comment]
Okie doke. Have had some discussion with @lukemelia about this and we've agreed that a sensible solution would be to add a function to [ember-cli-deploy/ember-cli-deploy-plugin](https://github.com/ember-cli-deploy/ember-cli-deploy-plugin) called `readConfigDefault`.

This function can be used to retrieve the default value for a particular config property. An example of it's usage might be as follows:

```javascript
// config/deploy.js

ENV.s3 = {
  filePattern: function(context, defaultValue) {
    return this.readConfigDefault('filePattern').replace('}', ',exe}');
  }
};
```

A couple of things to consider here:

1. This function should resolve the default config property the same way that `this.readConfig` does, ie, it will execute a function if needed, otherwise return the property.
2. Not every property has a default value. Calling this for such a property, or a required property will a `null` value.
3. There is an edge case (it may be less "edge" that we think) where, if a plugin author has chosen to not use the base plugin, or chosen to implement the default config functionality a different way, when a consumer tries to use `this.readConfigDefault` things will blow up. It means that a consumer of a plugin needs to understand whether it has been implemented using the base plugin or not which feels a little strange. We need to understand the ramifications of this, whether we need to worry about it and what the best way around it is.

**Comment by achambers** [comment]
I actually have a spare hour or two this evening (very very rare for this to be the case) so I'll have a quick look now and see if I can knock something out.

**Comment by achambers** [comment]
Ok, did some investigation around the above solution, and chatted it through with @lukemelia and we've agreed that the above solution maybe isn't as sensible as first thought. While trying to understand what the effects would be for a consumer that referenced `this.readConfigDefault` for a plugin that doesn't use the base plugin, I realised that, by implementing the solution above we'd be changing the context of `this` in the config property function to the plugin, which probably isn't what you would guess the context would be. The sensible value for `this` that one might expect is to be the object containing the property.

So, instead of the above solution we are going to pass a second argument in to the function, next to the `context`. This object will by default provide the ability to retrieve the default config. Something like:

```
ENV.foo = {
  bar: function(context, pluginHelper) {
    return pluginHelper.readConfigDefault('bar');
  }
};
```

As well as the default config, plugin authors that use the base plugin will have the opportunity to add other helper properties and functions that will be available on this object as well.

This does still leave us with a slight edge case problem, however, this problem already exists for us with the `context` object, or even the fact that consumers may define config properties as functions.

Currently if a consumer does define a function, but the plugin author does not use the base plugin, or does not use the `this.readConfig()` function, we are assuming that they will check to see if the config property is a function and, if so, execute it. We are also assuming that they will pass the `context` in if they do execute it.

So, there is already an edge case here that exists. We won't be making it any worse. And the fact that we've not yet heard of it does suggest that most people creating addons are using the base plugin.

**Comment by jrjohnson** [comment]
I didn't realize that it was possible, already, to return a callback for a config property.  In that case then adding an additional property to this seems very backwards compatible and easy to use.  

If there is a chance that future methods might get tacked on to this then passing it as `pluginHelper` will make it easy to add things, however then you have to worry about the API of the sent object.  If something ever gets removed it would be a very difficult to detect breaking change across a lot of surface.

**Comment by achambers** [comment]
The reason we'll be passing `pluginHelper` as opposed to the plugin itself is for that very reason. To limit the surface area to the minimal API needed. 

(As for the functions. You learn something new every day ;) ) As long as the plugin author uses `this.readConfig`, the function will executed at runtime with the current do text passed in. It's all in the docs ;)

**Comment by jrjohnson** [comment]
This is resolved with https://github.com/ember-cli-deploy/ember-cli-deploy-plugin/pull/15
