### ISSUE TITLE
add a verbose flag

### ISSUE THREAD

**Issue by samselikoff** [ember-cli-deploy/ember-cli-deploy#6]
First time I tried `deploy:assets`, program hung on "Uploading assets..."

**Comment by marcoow** [comment]
Having a `--verbose` option would be really cool. I'm just having a problem where I'm deploying `ember deploy --environment staging` but somehow it seems to build the project for the development environment although `buildEnv` is configured as `"staging"` - would be really helpful to see what's actually happening in order to track that down.

**Comment by michaelkelly322** [comment]
I just ran across this @marcoow in one of my projects.  It seems that `buildEnv` sets the target for ember-cli-deploy, but not for ember-cli-deploy-build.  The later bases its environment off of a `build.environment` key.  So in your staging config in `config/deploy.js` add:

```javascript
buildEnv: 'staging',
build: {
  environment: 'staging'
},
```

Not very DRY I know, but it did the trick for us :)
